name: Check and Format Markdown/Text

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Prettier
        run: npm install -g prettier

      - name: Format Markdown/Text files
        run: |
          echo "Running Prettier --write to auto-format files..."
          prettier --write "**/*.{md,txt}" --ignore-unknown || true

      - name: Verify formatting (non-blocking)
        run: |
          echo "Checking formatting (will not fail CI)..."
          prettier --check "**/*.{md,txt}" --ignore-unknown || true
