name: Commit Lint

on:
  pull_request:
    branches: [main, develop]

jobs:
  commitlint:
    name: Commit Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.mjs
